/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(extract_meta_vector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8ede41c7a9762f9b1f09d7a903d2b74d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/extract_meta_vector.h>
// pydoc.h is automatically generated in the build directory
#include <extract_meta_vector_pydoc.h>

void bind_extract_meta_vector(py::module& m)
{

    using extract_meta_vector = ::gr::ieee802_11::extract_meta_vector;


    py::class_<extract_meta_vector,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<extract_meta_vector>>(
        m, "extract_meta_vector", D(extract_meta_vector))

        .def(py::init(&extract_meta_vector::make),
             py::arg("key") = "csi",
             D(extract_meta_vector, make))


        ;
}
