/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_equalizer_tap.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(32b5bcf565c528cbbdfcf647fc7e9935)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/frame_equalizer_tap.h>
// pydoc.h is automatically generated in the build directory
#include <frame_equalizer_tap_pydoc.h>

void bind_frame_equalizer_tap(py::module& m)
{

    using frame_equalizer_tap = ::gr::ieee802_11::frame_equalizer_tap;


    py::class_<frame_equalizer_tap,
               gr::block,
               gr::basic_block,
               std::shared_ptr<frame_equalizer_tap>>(
        m, "frame_equalizer_tap", D(frame_equalizer_tap))

        .def(py::init(&frame_equalizer_tap::make),
             py::arg("algo"),
             py::arg("freq"),
             py::arg("bw"),
             py::arg("log"),
             py::arg("debug"),
             D(frame_equalizer_tap, make))


        .def("set_algorithm",
             &frame_equalizer_tap::set_algorithm,
             py::arg("algo"),
             D(frame_equalizer_tap, set_algorithm))


        .def("set_bandwidth",
             &frame_equalizer_tap::set_bandwidth,
             py::arg("bw"),
             D(frame_equalizer_tap, set_bandwidth))


        .def("set_frequency",
             &frame_equalizer_tap::set_frequency,
             py::arg("freq"),
             D(frame_equalizer_tap, set_frequency))

        ;

    py::enum_<::gr::ieee802_11::Equalizer>(m, "Equalizer")
        .value("LS", ::gr::ieee802_11::Equalizer::LS)     // 0
        .value("LMS", ::gr::ieee802_11::Equalizer::LMS)   // 1
        .value("COMB", ::gr::ieee802_11::Equalizer::COMB) // 2
        .value("STA", ::gr::ieee802_11::Equalizer::STA)   // 3
        .export_values();

    py::implicitly_convertible<int, ::gr::ieee802_11::Equalizer>();
}
